#!/usr/bin/python3

import os
import sys

# Check root
if os.getuid() != 0:
    import subprocess
    sp = subprocess.run(["pkexec", __file__])
    exit(sp.returncode)

sys.path.insert(0, '/usr/share/eta/eta-shutdown/src/')
import Main

